// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hnfqefablnqakjrgpxjt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhuZnFlZmFibG5xYWtqcmdweGp0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc2NjYyNzQsImV4cCI6MjA3MzI0MjI3NH0.2e7j-43iP6z8Yn_jHdIFjCfPDpN2Vwp7Q_DYJ2HXslQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});